-- Enable PostGIS for spatial queries
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================
-- SUBSIDIARIES
-- ============================================
CREATE TABLE IF NOT EXISTS subsidiaries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- USERS
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_MINER',
    mine_id INTEGER,
    subsidiary_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- MINES
-- ============================================
CREATE TABLE IF NOT EXISTS mines (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    subsidiary_id INTEGER,
    status VARCHAR(50) DEFAULT 'active',
    location GEOMETRY(Point, 4326),
    boundary GEOMETRY(Polygon, 4326),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ============================================
-- INCIDENTS
-- watermelon_id: UUID generated by mobile (WatermelonDB)
-- deleted_at: soft-delete for sync
-- ============================================
CREATE TABLE IF NOT EXISTS incidents (
    id SERIAL PRIMARY KEY,
    watermelon_id VARCHAR(36) UNIQUE,
    mine_id INTEGER REFERENCES mines(id) ON DELETE CASCADE,
    reported_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    severity VARCHAR(50) DEFAULT 'low',
    status VARCHAR(50) DEFAULT 'open',
    location GEOMETRY(Point, 4326),
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ============================================
-- INSPECTIONS
-- watermelon_id: UUID generated by mobile (WatermelonDB)
-- deleted_at: soft-delete for sync
-- ============================================
CREATE TABLE IF NOT EXISTS inspections (
    id SERIAL PRIMARY KEY,
    watermelon_id VARCHAR(36) UNIQUE,
    mine_id INTEGER REFERENCES mines(id) ON DELETE CASCADE,
    inspector_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'pending',
    notes TEXT,
    inspection_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- ============================================
-- VENTILATION SHAFTS
-- Used for the "500m proximity" spatial query
-- ============================================
CREATE TABLE IF NOT EXISTS ventilation_shafts (
    id SERIAL PRIMARY KEY,
    mine_id INTEGER REFERENCES mines(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    location GEOMETRY(Point, 4326),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- FOREIGN KEYS (added separately for IF NOT EXISTS tables)
-- ============================================
-- These use DO blocks so they don't fail if already added
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mines_subsidiary') THEN
        ALTER TABLE mines ADD CONSTRAINT fk_mines_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiaries(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_mine') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_mine FOREIGN KEY (mine_id) REFERENCES mines(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_subsidiary') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_subsidiary FOREIGN KEY (subsidiary_id) REFERENCES subsidiaries(id) ON DELETE SET NULL;
    END IF;
END $$;

-- ============================================
-- INDEXES for performance
-- ============================================
CREATE INDEX IF NOT EXISTS idx_incidents_mine_id ON incidents(mine_id);
CREATE INDEX IF NOT EXISTS idx_incidents_watermelon_id ON incidents(watermelon_id);
CREATE INDEX IF NOT EXISTS idx_incidents_updated_at ON incidents(updated_at);
CREATE INDEX IF NOT EXISTS idx_inspections_mine_id ON inspections(mine_id);
CREATE INDEX IF NOT EXISTS idx_inspections_watermelon_id ON inspections(watermelon_id);
CREATE INDEX IF NOT EXISTS idx_inspections_updated_at ON inspections(updated_at);
CREATE INDEX IF NOT EXISTS idx_users_mine_id ON users(mine_id);

-- Spatial indexes (GIST) for PostGIS queries
CREATE INDEX IF NOT EXISTS idx_incidents_location ON incidents USING GIST(location);
CREATE INDEX IF NOT EXISTS idx_mines_location ON mines USING GIST(location);
CREATE INDEX IF NOT EXISTS idx_mines_boundary ON mines USING GIST(boundary);
CREATE INDEX IF NOT EXISTS idx_shafts_location ON ventilation_shafts USING GIST(location);
